services:
  selenoid:
    image: aerokube/selenoid:latest
    container_name: selenoid
    # Заменяем network_mode: bridge на общую сеть:
    networks:
      - qa-network
    ports:
      - "4445:4444"
    environment:
      - DOCKER_API_VERSION=1.40
      - OVERRIDE_VIDEO_OUTPUT_DIR=/c/Users/laten/IdeaProjects/AQA-Petproject/infrastructure/selenoid/video
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/etc/selenoid/:ro
      - ./video:/opt/selenoid/video
    command: [ "-limit", "3" ]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest
    container_name: selenoid-ui
    networks:
      - qa-network
    links:
      - selenoid
    ports:
      - "8081:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]

  jenkins:
    image: jenkins/jenkins:lts-jdk21
    container_name: jenkins
    networks:
      - qa-network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home:

# ОБЪЯВЛЯЕМ СЕТЬ ТУТ
networks:
  qa-network:
    driver: bridge